// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mua/im_ap.proto

package ap

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushMsgReq struct {
	Fid                  int64    `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	SrvName              string   `protobuf:"bytes,2,opt,name=srvName,proto3" json:"srvName,omitempty"`
	MethodName           string   `protobuf:"bytes,3,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f9886a9770c7491, []int{0}
}

func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (m *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(m, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetFid() int64 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *PushMsgReq) GetSrvName() string {
	if m != nil {
		return m.SrvName
	}
	return ""
}

func (m *PushMsgReq) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *PushMsgReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PushMsgRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgRsp) Reset()         { *m = PushMsgRsp{} }
func (m *PushMsgRsp) String() string { return proto.CompactTextString(m) }
func (*PushMsgRsp) ProtoMessage()    {}
func (*PushMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f9886a9770c7491, []int{1}
}

func (m *PushMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgRsp.Unmarshal(m, b)
}
func (m *PushMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgRsp.Marshal(b, m, deterministic)
}
func (m *PushMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgRsp.Merge(m, src)
}
func (m *PushMsgRsp) XXX_Size() int {
	return xxx_messageInfo_PushMsgRsp.Size(m)
}
func (m *PushMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PushMsgReq)(nil), "mua.im.ap.PushMsgReq")
	proto.RegisterType((*PushMsgRsp)(nil), "mua.im.ap.PushMsgRsp")
}

func init() { proto.RegisterFile("mua/im_ap.proto", fileDescriptor_1f9886a9770c7491) }

var fileDescriptor_1f9886a9770c7491 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x2d, 0x4d, 0xd4,
	0xcf, 0xcc, 0x8d, 0x4f, 0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0x2d, 0x4d,
	0xd4, 0xcb, 0xcc, 0xd5, 0x4b, 0x2c, 0x50, 0xca, 0xe1, 0xe2, 0x0a, 0x28, 0x2d, 0xce, 0xf0, 0x2d,
	0x4e, 0x0f, 0x4a, 0x2d, 0x14, 0x12, 0xe0, 0x62, 0x4e, 0xcb, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0e, 0x02, 0x31, 0x85, 0x24, 0xb8, 0xd8, 0x8b, 0x8b, 0xca, 0xfc, 0x12, 0x73, 0x53, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x39, 0x2e, 0xae, 0xdc, 0xd4, 0x92, 0x8c,
	0xfc, 0x14, 0xb0, 0x24, 0x33, 0x58, 0x12, 0x49, 0x44, 0x48, 0x88, 0x8b, 0xc5, 0x25, 0xb1, 0x24,
	0x51, 0x82, 0x45, 0x81, 0x51, 0x83, 0x27, 0x08, 0xcc, 0x56, 0xe2, 0x41, 0xd8, 0x56, 0x5c, 0x60,
	0x64, 0xcb, 0xc5, 0xe4, 0x18, 0x20, 0x64, 0xce, 0xc5, 0x0e, 0x15, 0x13, 0x12, 0xd5, 0x83, 0x3b,
	0x4c, 0x0f, 0xe1, 0x2a, 0x29, 0x6c, 0xc2, 0xc5, 0x05, 0x4e, 0xdc, 0x51, 0x9c, 0x10, 0x8f, 0xe9,
	0x27, 0x16, 0x24, 0xb1, 0x81, 0x7d, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x02, 0x78, 0x10,
	0x56, 0xec, 0x00, 0x00, 0x00,
}
