// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mua/im_relation.proto

package relation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupType int32

const (
	GroupType_GroupTypeUnknown GroupType = 0
	GroupType_Temporary        GroupType = 1
	GroupType_General          GroupType = 2
	GroupType_Super            GroupType = 3
)

var GroupType_name = map[int32]string{
	0: "GroupTypeUnknown",
	1: "Temporary",
	2: "General",
	3: "Super",
}

var GroupType_value = map[string]int32{
	"GroupTypeUnknown": 0,
	"Temporary":        1,
	"General":          2,
	"Super":            3,
}

func (x GroupType) String() string {
	return proto.EnumName(GroupType_name, int32(x))
}

func (GroupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{0}
}

//群组关系类型
type GroupRoleType int32

const (
	GroupRoleType_GroupRoleTypeUnknow GroupRoleType = 0
	GroupRoleType_GeneralMember       GroupRoleType = 1
	GroupRoleType_Owner               GroupRoleType = 2
	GroupRoleType_Manager             GroupRoleType = 3
)

var GroupRoleType_name = map[int32]string{
	0: "GroupRoleTypeUnknow",
	1: "GeneralMember",
	2: "Owner",
	3: "Manager",
}

var GroupRoleType_value = map[string]int32{
	"GroupRoleTypeUnknow": 0,
	"GeneralMember":       1,
	"Owner":               2,
	"Manager":             3,
}

func (x GroupRoleType) String() string {
	return proto.EnumName(GroupRoleType_name, int32(x))
}

func (GroupRoleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{1}
}

type PersonalRelationType int32

const (
	PersonalRelationType_PersonalRelationTypeUnknown PersonalRelationType = 0
	PersonalRelationType_Followed                    PersonalRelationType = 1
	PersonalRelationType_Friended                    PersonalRelationType = 2
	PersonalRelationType_Blocked                     PersonalRelationType = 3
)

var PersonalRelationType_name = map[int32]string{
	0: "PersonalRelationTypeUnknown",
	1: "Followed",
	2: "Friended",
	3: "Blocked",
}

var PersonalRelationType_value = map[string]int32{
	"PersonalRelationTypeUnknown": 0,
	"Followed":                    1,
	"Friended":                    2,
	"Blocked":                     3,
}

func (x PersonalRelationType) String() string {
	return proto.EnumName(PersonalRelationType_name, int32(x))
}

func (PersonalRelationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{2}
}

type Group struct {
	ID                   int64     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notice               string    `protobuf:"bytes,3,opt,name=notice,proto3" json:"notice,omitempty"`
	CreatedAt            int64     `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Type                 GroupType `protobuf:"varint,5,opt,name=type,proto3,enum=mua.im.relation.GroupType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *Group) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Group) GetType() GroupType {
	if m != nil {
		return m.Type
	}
	return GroupType_GroupTypeUnknown
}

//个人关系
type PersonalRelation struct {
	//string ID               = 1; //关系实例ID
	SrcUID               int64    `protobuf:"varint,2,opt,name=srcUID,proto3" json:"srcUID,omitempty"`
	DstUID               int64    `protobuf:"varint,3,opt,name=dstUID,proto3" json:"dstUID,omitempty"`
	IsFollow             bool     `protobuf:"varint,4,opt,name=isFollow,proto3" json:"isFollow,omitempty"`
	IsFriend             bool     `protobuf:"varint,5,opt,name=isFriend,proto3" json:"isFriend,omitempty"`
	IsBlock              bool     `protobuf:"varint,6,opt,name=isBlock,proto3" json:"isBlock,omitempty"`
	Remark               string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Tag                  []string `protobuf:"bytes,8,rep,name=tag,proto3" json:"tag,omitempty"`
	Desc                 string   `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`
	FollowAt             int64    `protobuf:"varint,10,opt,name=followAt,proto3" json:"followAt,omitempty"`
	FriendAt             int64    `protobuf:"varint,11,opt,name=friendAt,proto3" json:"friendAt,omitempty"`
	BlockAt              int64    `protobuf:"varint,12,opt,name=blockAt,proto3" json:"blockAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonalRelation) Reset()         { *m = PersonalRelation{} }
func (m *PersonalRelation) String() string { return proto.CompactTextString(m) }
func (*PersonalRelation) ProtoMessage()    {}
func (*PersonalRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{1}
}

func (m *PersonalRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalRelation.Unmarshal(m, b)
}
func (m *PersonalRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalRelation.Marshal(b, m, deterministic)
}
func (m *PersonalRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalRelation.Merge(m, src)
}
func (m *PersonalRelation) XXX_Size() int {
	return xxx_messageInfo_PersonalRelation.Size(m)
}
func (m *PersonalRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalRelation.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalRelation proto.InternalMessageInfo

func (m *PersonalRelation) GetSrcUID() int64 {
	if m != nil {
		return m.SrcUID
	}
	return 0
}

func (m *PersonalRelation) GetDstUID() int64 {
	if m != nil {
		return m.DstUID
	}
	return 0
}

func (m *PersonalRelation) GetIsFollow() bool {
	if m != nil {
		return m.IsFollow
	}
	return false
}

func (m *PersonalRelation) GetIsFriend() bool {
	if m != nil {
		return m.IsFriend
	}
	return false
}

func (m *PersonalRelation) GetIsBlock() bool {
	if m != nil {
		return m.IsBlock
	}
	return false
}

func (m *PersonalRelation) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *PersonalRelation) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *PersonalRelation) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *PersonalRelation) GetFollowAt() int64 {
	if m != nil {
		return m.FollowAt
	}
	return 0
}

func (m *PersonalRelation) GetFriendAt() int64 {
	if m != nil {
		return m.FriendAt
	}
	return 0
}

func (m *PersonalRelation) GetBlockAt() int64 {
	if m != nil {
		return m.BlockAt
	}
	return 0
}

//群组关系
type GroupRelation struct {
	//string          ID               = 1; //关系实例ID
	SrcUID               int64         `protobuf:"varint,2,opt,name=srcUID,proto3" json:"srcUID,omitempty"`
	GroupID              int64         `protobuf:"varint,3,opt,name=groupID,proto3" json:"groupID,omitempty"`
	JoinAt               int64         `protobuf:"varint,4,opt,name=joinAt,proto3" json:"joinAt,omitempty"`
	Role                 GroupRoleType `protobuf:"varint,5,opt,name=role,proto3,enum=mua.im.relation.GroupRoleType" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GroupRelation) Reset()         { *m = GroupRelation{} }
func (m *GroupRelation) String() string { return proto.CompactTextString(m) }
func (*GroupRelation) ProtoMessage()    {}
func (*GroupRelation) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{2}
}

func (m *GroupRelation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupRelation.Unmarshal(m, b)
}
func (m *GroupRelation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupRelation.Marshal(b, m, deterministic)
}
func (m *GroupRelation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupRelation.Merge(m, src)
}
func (m *GroupRelation) XXX_Size() int {
	return xxx_messageInfo_GroupRelation.Size(m)
}
func (m *GroupRelation) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupRelation.DiscardUnknown(m)
}

var xxx_messageInfo_GroupRelation proto.InternalMessageInfo

func (m *GroupRelation) GetSrcUID() int64 {
	if m != nil {
		return m.SrcUID
	}
	return 0
}

func (m *GroupRelation) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *GroupRelation) GetJoinAt() int64 {
	if m != nil {
		return m.JoinAt
	}
	return 0
}

func (m *GroupRelation) GetRole() GroupRoleType {
	if m != nil {
		return m.Role
	}
	return GroupRoleType_GroupRoleTypeUnknow
}

type FollowReq struct {
	SrcUID               int64    `protobuf:"varint,1,opt,name=srcUID,proto3" json:"srcUID,omitempty"`
	DstUID               int64    `protobuf:"varint,2,opt,name=dstUID,proto3" json:"dstUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowReq) Reset()         { *m = FollowReq{} }
func (m *FollowReq) String() string { return proto.CompactTextString(m) }
func (*FollowReq) ProtoMessage()    {}
func (*FollowReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{3}
}

func (m *FollowReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowReq.Unmarshal(m, b)
}
func (m *FollowReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowReq.Marshal(b, m, deterministic)
}
func (m *FollowReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowReq.Merge(m, src)
}
func (m *FollowReq) XXX_Size() int {
	return xxx_messageInfo_FollowReq.Size(m)
}
func (m *FollowReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowReq.DiscardUnknown(m)
}

var xxx_messageInfo_FollowReq proto.InternalMessageInfo

func (m *FollowReq) GetSrcUID() int64 {
	if m != nil {
		return m.SrcUID
	}
	return 0
}

func (m *FollowReq) GetDstUID() int64 {
	if m != nil {
		return m.DstUID
	}
	return 0
}

type FollowRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowRsp) Reset()         { *m = FollowRsp{} }
func (m *FollowRsp) String() string { return proto.CompactTextString(m) }
func (*FollowRsp) ProtoMessage()    {}
func (*FollowRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{4}
}

func (m *FollowRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRsp.Unmarshal(m, b)
}
func (m *FollowRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRsp.Marshal(b, m, deterministic)
}
func (m *FollowRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRsp.Merge(m, src)
}
func (m *FollowRsp) XXX_Size() int {
	return xxx_messageInfo_FollowRsp.Size(m)
}
func (m *FollowRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRsp proto.InternalMessageInfo

type UnfollowReq struct {
	SrcUID               int64    `protobuf:"varint,1,opt,name=srcUID,proto3" json:"srcUID,omitempty"`
	DstUID               int64    `protobuf:"varint,2,opt,name=dstUID,proto3" json:"dstUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfollowReq) Reset()         { *m = UnfollowReq{} }
func (m *UnfollowReq) String() string { return proto.CompactTextString(m) }
func (*UnfollowReq) ProtoMessage()    {}
func (*UnfollowReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{5}
}

func (m *UnfollowReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfollowReq.Unmarshal(m, b)
}
func (m *UnfollowReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfollowReq.Marshal(b, m, deterministic)
}
func (m *UnfollowReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfollowReq.Merge(m, src)
}
func (m *UnfollowReq) XXX_Size() int {
	return xxx_messageInfo_UnfollowReq.Size(m)
}
func (m *UnfollowReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfollowReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnfollowReq proto.InternalMessageInfo

func (m *UnfollowReq) GetSrcUID() int64 {
	if m != nil {
		return m.SrcUID
	}
	return 0
}

func (m *UnfollowReq) GetDstUID() int64 {
	if m != nil {
		return m.DstUID
	}
	return 0
}

type UnfollowRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfollowRsp) Reset()         { *m = UnfollowRsp{} }
func (m *UnfollowRsp) String() string { return proto.CompactTextString(m) }
func (*UnfollowRsp) ProtoMessage()    {}
func (*UnfollowRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{6}
}

func (m *UnfollowRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfollowRsp.Unmarshal(m, b)
}
func (m *UnfollowRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfollowRsp.Marshal(b, m, deterministic)
}
func (m *UnfollowRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfollowRsp.Merge(m, src)
}
func (m *UnfollowRsp) XXX_Size() int {
	return xxx_messageInfo_UnfollowRsp.Size(m)
}
func (m *UnfollowRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfollowRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UnfollowRsp proto.InternalMessageInfo

type BlockReq struct {
	SrcUID               int64    `protobuf:"varint,1,opt,name=srcUID,proto3" json:"srcUID,omitempty"`
	DstUID               int64    `protobuf:"varint,2,opt,name=dstUID,proto3" json:"dstUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockReq) Reset()         { *m = BlockReq{} }
func (m *BlockReq) String() string { return proto.CompactTextString(m) }
func (*BlockReq) ProtoMessage()    {}
func (*BlockReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{7}
}

func (m *BlockReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockReq.Unmarshal(m, b)
}
func (m *BlockReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockReq.Marshal(b, m, deterministic)
}
func (m *BlockReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockReq.Merge(m, src)
}
func (m *BlockReq) XXX_Size() int {
	return xxx_messageInfo_BlockReq.Size(m)
}
func (m *BlockReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlockReq proto.InternalMessageInfo

func (m *BlockReq) GetSrcUID() int64 {
	if m != nil {
		return m.SrcUID
	}
	return 0
}

func (m *BlockReq) GetDstUID() int64 {
	if m != nil {
		return m.DstUID
	}
	return 0
}

type BlockRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRsp) Reset()         { *m = BlockRsp{} }
func (m *BlockRsp) String() string { return proto.CompactTextString(m) }
func (*BlockRsp) ProtoMessage()    {}
func (*BlockRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{8}
}

func (m *BlockRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRsp.Unmarshal(m, b)
}
func (m *BlockRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRsp.Marshal(b, m, deterministic)
}
func (m *BlockRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRsp.Merge(m, src)
}
func (m *BlockRsp) XXX_Size() int {
	return xxx_messageInfo_BlockRsp.Size(m)
}
func (m *BlockRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRsp proto.InternalMessageInfo

type UnblockReq struct {
	SrcUID               int64    `protobuf:"varint,1,opt,name=srcUID,proto3" json:"srcUID,omitempty"`
	DstUID               int64    `protobuf:"varint,2,opt,name=dstUID,proto3" json:"dstUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnblockReq) Reset()         { *m = UnblockReq{} }
func (m *UnblockReq) String() string { return proto.CompactTextString(m) }
func (*UnblockReq) ProtoMessage()    {}
func (*UnblockReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{9}
}

func (m *UnblockReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnblockReq.Unmarshal(m, b)
}
func (m *UnblockReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnblockReq.Marshal(b, m, deterministic)
}
func (m *UnblockReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnblockReq.Merge(m, src)
}
func (m *UnblockReq) XXX_Size() int {
	return xxx_messageInfo_UnblockReq.Size(m)
}
func (m *UnblockReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnblockReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnblockReq proto.InternalMessageInfo

func (m *UnblockReq) GetSrcUID() int64 {
	if m != nil {
		return m.SrcUID
	}
	return 0
}

func (m *UnblockReq) GetDstUID() int64 {
	if m != nil {
		return m.DstUID
	}
	return 0
}

type UnblockRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnblockRsp) Reset()         { *m = UnblockRsp{} }
func (m *UnblockRsp) String() string { return proto.CompactTextString(m) }
func (*UnblockRsp) ProtoMessage()    {}
func (*UnblockRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{10}
}

func (m *UnblockRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnblockRsp.Unmarshal(m, b)
}
func (m *UnblockRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnblockRsp.Marshal(b, m, deterministic)
}
func (m *UnblockRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnblockRsp.Merge(m, src)
}
func (m *UnblockRsp) XXX_Size() int {
	return xxx_messageInfo_UnblockRsp.Size(m)
}
func (m *UnblockRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnblockRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UnblockRsp proto.InternalMessageInfo

type GetPersonalRelationReq struct {
	SrcUID               int64    `protobuf:"varint,1,opt,name=srcUID,proto3" json:"srcUID,omitempty"`
	DstUID               int64    `protobuf:"varint,2,opt,name=dstUID,proto3" json:"dstUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonalRelationReq) Reset()         { *m = GetPersonalRelationReq{} }
func (m *GetPersonalRelationReq) String() string { return proto.CompactTextString(m) }
func (*GetPersonalRelationReq) ProtoMessage()    {}
func (*GetPersonalRelationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{11}
}

func (m *GetPersonalRelationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonalRelationReq.Unmarshal(m, b)
}
func (m *GetPersonalRelationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonalRelationReq.Marshal(b, m, deterministic)
}
func (m *GetPersonalRelationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonalRelationReq.Merge(m, src)
}
func (m *GetPersonalRelationReq) XXX_Size() int {
	return xxx_messageInfo_GetPersonalRelationReq.Size(m)
}
func (m *GetPersonalRelationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonalRelationReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonalRelationReq proto.InternalMessageInfo

func (m *GetPersonalRelationReq) GetSrcUID() int64 {
	if m != nil {
		return m.SrcUID
	}
	return 0
}

func (m *GetPersonalRelationReq) GetDstUID() int64 {
	if m != nil {
		return m.DstUID
	}
	return 0
}

type GetPersonalRelationRsp struct {
	Info                 *PersonalRelation `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPersonalRelationRsp) Reset()         { *m = GetPersonalRelationRsp{} }
func (m *GetPersonalRelationRsp) String() string { return proto.CompactTextString(m) }
func (*GetPersonalRelationRsp) ProtoMessage()    {}
func (*GetPersonalRelationRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{12}
}

func (m *GetPersonalRelationRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonalRelationRsp.Unmarshal(m, b)
}
func (m *GetPersonalRelationRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonalRelationRsp.Marshal(b, m, deterministic)
}
func (m *GetPersonalRelationRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonalRelationRsp.Merge(m, src)
}
func (m *GetPersonalRelationRsp) XXX_Size() int {
	return xxx_messageInfo_GetPersonalRelationRsp.Size(m)
}
func (m *GetPersonalRelationRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonalRelationRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonalRelationRsp proto.InternalMessageInfo

func (m *GetPersonalRelationRsp) GetInfo() *PersonalRelation {
	if m != nil {
		return m.Info
	}
	return nil
}

type ListPersonalRelationReq struct {
	UID                  int64                `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Type                 PersonalRelationType `protobuf:"varint,2,opt,name=type,proto3,enum=mua.im.relation.PersonalRelationType" json:"type,omitempty"`
	Page                 int32                `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32                `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListPersonalRelationReq) Reset()         { *m = ListPersonalRelationReq{} }
func (m *ListPersonalRelationReq) String() string { return proto.CompactTextString(m) }
func (*ListPersonalRelationReq) ProtoMessage()    {}
func (*ListPersonalRelationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{13}
}

func (m *ListPersonalRelationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPersonalRelationReq.Unmarshal(m, b)
}
func (m *ListPersonalRelationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPersonalRelationReq.Marshal(b, m, deterministic)
}
func (m *ListPersonalRelationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPersonalRelationReq.Merge(m, src)
}
func (m *ListPersonalRelationReq) XXX_Size() int {
	return xxx_messageInfo_ListPersonalRelationReq.Size(m)
}
func (m *ListPersonalRelationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPersonalRelationReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPersonalRelationReq proto.InternalMessageInfo

func (m *ListPersonalRelationReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *ListPersonalRelationReq) GetType() PersonalRelationType {
	if m != nil {
		return m.Type
	}
	return PersonalRelationType_PersonalRelationTypeUnknown
}

func (m *ListPersonalRelationReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListPersonalRelationReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListPersonalRelationRsp struct {
	Infos                []*PersonalRelation `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	Total                int32               `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListPersonalRelationRsp) Reset()         { *m = ListPersonalRelationRsp{} }
func (m *ListPersonalRelationRsp) String() string { return proto.CompactTextString(m) }
func (*ListPersonalRelationRsp) ProtoMessage()    {}
func (*ListPersonalRelationRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{14}
}

func (m *ListPersonalRelationRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPersonalRelationRsp.Unmarshal(m, b)
}
func (m *ListPersonalRelationRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPersonalRelationRsp.Marshal(b, m, deterministic)
}
func (m *ListPersonalRelationRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPersonalRelationRsp.Merge(m, src)
}
func (m *ListPersonalRelationRsp) XXX_Size() int {
	return xxx_messageInfo_ListPersonalRelationRsp.Size(m)
}
func (m *ListPersonalRelationRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPersonalRelationRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ListPersonalRelationRsp proto.InternalMessageInfo

func (m *ListPersonalRelationRsp) GetInfos() []*PersonalRelation {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *ListPersonalRelationRsp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type JoinGroupReq struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	GroupID              int64    `protobuf:"varint,2,opt,name=groupID,proto3" json:"groupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGroupReq) Reset()         { *m = JoinGroupReq{} }
func (m *JoinGroupReq) String() string { return proto.CompactTextString(m) }
func (*JoinGroupReq) ProtoMessage()    {}
func (*JoinGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{15}
}

func (m *JoinGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGroupReq.Unmarshal(m, b)
}
func (m *JoinGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGroupReq.Marshal(b, m, deterministic)
}
func (m *JoinGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGroupReq.Merge(m, src)
}
func (m *JoinGroupReq) XXX_Size() int {
	return xxx_messageInfo_JoinGroupReq.Size(m)
}
func (m *JoinGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGroupReq proto.InternalMessageInfo

func (m *JoinGroupReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *JoinGroupReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

type JoinGroupRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGroupRsp) Reset()         { *m = JoinGroupRsp{} }
func (m *JoinGroupRsp) String() string { return proto.CompactTextString(m) }
func (*JoinGroupRsp) ProtoMessage()    {}
func (*JoinGroupRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{16}
}

func (m *JoinGroupRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGroupRsp.Unmarshal(m, b)
}
func (m *JoinGroupRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGroupRsp.Marshal(b, m, deterministic)
}
func (m *JoinGroupRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGroupRsp.Merge(m, src)
}
func (m *JoinGroupRsp) XXX_Size() int {
	return xxx_messageInfo_JoinGroupRsp.Size(m)
}
func (m *JoinGroupRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGroupRsp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGroupRsp proto.InternalMessageInfo

func (m *JoinGroupRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type QuitGroupReq struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	GroupID              int64    `protobuf:"varint,2,opt,name=groupID,proto3" json:"groupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupReq) Reset()         { *m = QuitGroupReq{} }
func (m *QuitGroupReq) String() string { return proto.CompactTextString(m) }
func (*QuitGroupReq) ProtoMessage()    {}
func (*QuitGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{17}
}

func (m *QuitGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupReq.Unmarshal(m, b)
}
func (m *QuitGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupReq.Marshal(b, m, deterministic)
}
func (m *QuitGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupReq.Merge(m, src)
}
func (m *QuitGroupReq) XXX_Size() int {
	return xxx_messageInfo_QuitGroupReq.Size(m)
}
func (m *QuitGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupReq proto.InternalMessageInfo

func (m *QuitGroupReq) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *QuitGroupReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

type QuitGroupRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupRsp) Reset()         { *m = QuitGroupRsp{} }
func (m *QuitGroupRsp) String() string { return proto.CompactTextString(m) }
func (*QuitGroupRsp) ProtoMessage()    {}
func (*QuitGroupRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{18}
}

func (m *QuitGroupRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupRsp.Unmarshal(m, b)
}
func (m *QuitGroupRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupRsp.Marshal(b, m, deterministic)
}
func (m *QuitGroupRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupRsp.Merge(m, src)
}
func (m *QuitGroupRsp) XXX_Size() int {
	return xxx_messageInfo_QuitGroupRsp.Size(m)
}
func (m *QuitGroupRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupRsp proto.InternalMessageInfo

type CreateGroupReq struct {
	SrcUID               int64    `protobuf:"varint,1,opt,name=srcUID,proto3" json:"srcUID,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupReq) Reset()         { *m = CreateGroupReq{} }
func (m *CreateGroupReq) String() string { return proto.CompactTextString(m) }
func (*CreateGroupReq) ProtoMessage()    {}
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{19}
}

func (m *CreateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupReq.Unmarshal(m, b)
}
func (m *CreateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupReq.Marshal(b, m, deterministic)
}
func (m *CreateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupReq.Merge(m, src)
}
func (m *CreateGroupReq) XXX_Size() int {
	return xxx_messageInfo_CreateGroupReq.Size(m)
}
func (m *CreateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupReq proto.InternalMessageInfo

func (m *CreateGroupReq) GetSrcUID() int64 {
	if m != nil {
		return m.SrcUID
	}
	return 0
}

func (m *CreateGroupReq) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type CreateGroupRsp struct {
	Info                 *Group   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRsp) Reset()         { *m = CreateGroupRsp{} }
func (m *CreateGroupRsp) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRsp) ProtoMessage()    {}
func (*CreateGroupRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{20}
}

func (m *CreateGroupRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRsp.Unmarshal(m, b)
}
func (m *CreateGroupRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRsp.Marshal(b, m, deterministic)
}
func (m *CreateGroupRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRsp.Merge(m, src)
}
func (m *CreateGroupRsp) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRsp.Size(m)
}
func (m *CreateGroupRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRsp proto.InternalMessageInfo

func (m *CreateGroupRsp) GetInfo() *Group {
	if m != nil {
		return m.Info
	}
	return nil
}

type ChangeGroupInfoReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Info                 *Group   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeGroupInfoReq) Reset()         { *m = ChangeGroupInfoReq{} }
func (m *ChangeGroupInfoReq) String() string { return proto.CompactTextString(m) }
func (*ChangeGroupInfoReq) ProtoMessage()    {}
func (*ChangeGroupInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{21}
}

func (m *ChangeGroupInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeGroupInfoReq.Unmarshal(m, b)
}
func (m *ChangeGroupInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeGroupInfoReq.Marshal(b, m, deterministic)
}
func (m *ChangeGroupInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeGroupInfoReq.Merge(m, src)
}
func (m *ChangeGroupInfoReq) XXX_Size() int {
	return xxx_messageInfo_ChangeGroupInfoReq.Size(m)
}
func (m *ChangeGroupInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeGroupInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeGroupInfoReq proto.InternalMessageInfo

func (m *ChangeGroupInfoReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ChangeGroupInfoReq) GetInfo() *Group {
	if m != nil {
		return m.Info
	}
	return nil
}

type ChangeGroupInfoRsp struct {
	Info                 *Group   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeGroupInfoRsp) Reset()         { *m = ChangeGroupInfoRsp{} }
func (m *ChangeGroupInfoRsp) String() string { return proto.CompactTextString(m) }
func (*ChangeGroupInfoRsp) ProtoMessage()    {}
func (*ChangeGroupInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{22}
}

func (m *ChangeGroupInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeGroupInfoRsp.Unmarshal(m, b)
}
func (m *ChangeGroupInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeGroupInfoRsp.Marshal(b, m, deterministic)
}
func (m *ChangeGroupInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeGroupInfoRsp.Merge(m, src)
}
func (m *ChangeGroupInfoRsp) XXX_Size() int {
	return xxx_messageInfo_ChangeGroupInfoRsp.Size(m)
}
func (m *ChangeGroupInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeGroupInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeGroupInfoRsp proto.InternalMessageInfo

func (m *ChangeGroupInfoRsp) GetInfo() *Group {
	if m != nil {
		return m.Info
	}
	return nil
}

type UpgradeGroupReq struct {
	GroupID              int64     `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Type                 GroupType `protobuf:"varint,2,opt,name=type,proto3,enum=mua.im.relation.GroupType" json:"type,omitempty"`
	Uid                  int64     `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpgradeGroupReq) Reset()         { *m = UpgradeGroupReq{} }
func (m *UpgradeGroupReq) String() string { return proto.CompactTextString(m) }
func (*UpgradeGroupReq) ProtoMessage()    {}
func (*UpgradeGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{23}
}

func (m *UpgradeGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeGroupReq.Unmarshal(m, b)
}
func (m *UpgradeGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeGroupReq.Marshal(b, m, deterministic)
}
func (m *UpgradeGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeGroupReq.Merge(m, src)
}
func (m *UpgradeGroupReq) XXX_Size() int {
	return xxx_messageInfo_UpgradeGroupReq.Size(m)
}
func (m *UpgradeGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeGroupReq proto.InternalMessageInfo

func (m *UpgradeGroupReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *UpgradeGroupReq) GetType() GroupType {
	if m != nil {
		return m.Type
	}
	return GroupType_GroupTypeUnknown
}

func (m *UpgradeGroupReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UpgradeGroupRsp struct {
	Info                 *Group   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeGroupRsp) Reset()         { *m = UpgradeGroupRsp{} }
func (m *UpgradeGroupRsp) String() string { return proto.CompactTextString(m) }
func (*UpgradeGroupRsp) ProtoMessage()    {}
func (*UpgradeGroupRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{24}
}

func (m *UpgradeGroupRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeGroupRsp.Unmarshal(m, b)
}
func (m *UpgradeGroupRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeGroupRsp.Marshal(b, m, deterministic)
}
func (m *UpgradeGroupRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeGroupRsp.Merge(m, src)
}
func (m *UpgradeGroupRsp) XXX_Size() int {
	return xxx_messageInfo_UpgradeGroupRsp.Size(m)
}
func (m *UpgradeGroupRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeGroupRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeGroupRsp proto.InternalMessageInfo

func (m *UpgradeGroupRsp) GetInfo() *Group {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetGroupReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupReq) Reset()         { *m = GetGroupReq{} }
func (m *GetGroupReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupReq) ProtoMessage()    {}
func (*GetGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{25}
}

func (m *GetGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupReq.Unmarshal(m, b)
}
func (m *GetGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupReq.Marshal(b, m, deterministic)
}
func (m *GetGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupReq.Merge(m, src)
}
func (m *GetGroupReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupReq.Size(m)
}
func (m *GetGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupReq proto.InternalMessageInfo

func (m *GetGroupReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

type GetGroupRsp struct {
	Info                 *Group   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRsp) Reset()         { *m = GetGroupRsp{} }
func (m *GetGroupRsp) String() string { return proto.CompactTextString(m) }
func (*GetGroupRsp) ProtoMessage()    {}
func (*GetGroupRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{26}
}

func (m *GetGroupRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRsp.Unmarshal(m, b)
}
func (m *GetGroupRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRsp.Marshal(b, m, deterministic)
}
func (m *GetGroupRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRsp.Merge(m, src)
}
func (m *GetGroupRsp) XXX_Size() int {
	return xxx_messageInfo_GetGroupRsp.Size(m)
}
func (m *GetGroupRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRsp proto.InternalMessageInfo

func (m *GetGroupRsp) GetInfo() *Group {
	if m != nil {
		return m.Info
	}
	return nil
}

type ListGroupMemberIDReq struct {
	GroupID              int64    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupMemberIDReq) Reset()         { *m = ListGroupMemberIDReq{} }
func (m *ListGroupMemberIDReq) String() string { return proto.CompactTextString(m) }
func (*ListGroupMemberIDReq) ProtoMessage()    {}
func (*ListGroupMemberIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{27}
}

func (m *ListGroupMemberIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupMemberIDReq.Unmarshal(m, b)
}
func (m *ListGroupMemberIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupMemberIDReq.Marshal(b, m, deterministic)
}
func (m *ListGroupMemberIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupMemberIDReq.Merge(m, src)
}
func (m *ListGroupMemberIDReq) XXX_Size() int {
	return xxx_messageInfo_ListGroupMemberIDReq.Size(m)
}
func (m *ListGroupMemberIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupMemberIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupMemberIDReq proto.InternalMessageInfo

func (m *ListGroupMemberIDReq) GetGroupID() int64 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *ListGroupMemberIDReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListGroupMemberIDReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListGroupMemberIDRsp struct {
	Uid                  []int64  `protobuf:"varint,1,rep,packed,name=uid,proto3" json:"uid,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupMemberIDRsp) Reset()         { *m = ListGroupMemberIDRsp{} }
func (m *ListGroupMemberIDRsp) String() string { return proto.CompactTextString(m) }
func (*ListGroupMemberIDRsp) ProtoMessage()    {}
func (*ListGroupMemberIDRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77be588edaa88f80, []int{28}
}

func (m *ListGroupMemberIDRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupMemberIDRsp.Unmarshal(m, b)
}
func (m *ListGroupMemberIDRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupMemberIDRsp.Marshal(b, m, deterministic)
}
func (m *ListGroupMemberIDRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupMemberIDRsp.Merge(m, src)
}
func (m *ListGroupMemberIDRsp) XXX_Size() int {
	return xxx_messageInfo_ListGroupMemberIDRsp.Size(m)
}
func (m *ListGroupMemberIDRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupMemberIDRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupMemberIDRsp proto.InternalMessageInfo

func (m *ListGroupMemberIDRsp) GetUid() []int64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *ListGroupMemberIDRsp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("mua.im.relation.GroupType", GroupType_name, GroupType_value)
	proto.RegisterEnum("mua.im.relation.GroupRoleType", GroupRoleType_name, GroupRoleType_value)
	proto.RegisterEnum("mua.im.relation.PersonalRelationType", PersonalRelationType_name, PersonalRelationType_value)
	proto.RegisterType((*Group)(nil), "mua.im.relation.Group")
	proto.RegisterType((*PersonalRelation)(nil), "mua.im.relation.PersonalRelation")
	proto.RegisterType((*GroupRelation)(nil), "mua.im.relation.GroupRelation")
	proto.RegisterType((*FollowReq)(nil), "mua.im.relation.FollowReq")
	proto.RegisterType((*FollowRsp)(nil), "mua.im.relation.FollowRsp")
	proto.RegisterType((*UnfollowReq)(nil), "mua.im.relation.UnfollowReq")
	proto.RegisterType((*UnfollowRsp)(nil), "mua.im.relation.UnfollowRsp")
	proto.RegisterType((*BlockReq)(nil), "mua.im.relation.BlockReq")
	proto.RegisterType((*BlockRsp)(nil), "mua.im.relation.BlockRsp")
	proto.RegisterType((*UnblockReq)(nil), "mua.im.relation.UnblockReq")
	proto.RegisterType((*UnblockRsp)(nil), "mua.im.relation.UnblockRsp")
	proto.RegisterType((*GetPersonalRelationReq)(nil), "mua.im.relation.GetPersonalRelationReq")
	proto.RegisterType((*GetPersonalRelationRsp)(nil), "mua.im.relation.GetPersonalRelationRsp")
	proto.RegisterType((*ListPersonalRelationReq)(nil), "mua.im.relation.ListPersonalRelationReq")
	proto.RegisterType((*ListPersonalRelationRsp)(nil), "mua.im.relation.ListPersonalRelationRsp")
	proto.RegisterType((*JoinGroupReq)(nil), "mua.im.relation.JoinGroupReq")
	proto.RegisterType((*JoinGroupRsp)(nil), "mua.im.relation.JoinGroupRsp")
	proto.RegisterType((*QuitGroupReq)(nil), "mua.im.relation.QuitGroupReq")
	proto.RegisterType((*QuitGroupRsp)(nil), "mua.im.relation.QuitGroupRsp")
	proto.RegisterType((*CreateGroupReq)(nil), "mua.im.relation.CreateGroupReq")
	proto.RegisterType((*CreateGroupRsp)(nil), "mua.im.relation.CreateGroupRsp")
	proto.RegisterType((*ChangeGroupInfoReq)(nil), "mua.im.relation.ChangeGroupInfoReq")
	proto.RegisterType((*ChangeGroupInfoRsp)(nil), "mua.im.relation.ChangeGroupInfoRsp")
	proto.RegisterType((*UpgradeGroupReq)(nil), "mua.im.relation.UpgradeGroupReq")
	proto.RegisterType((*UpgradeGroupRsp)(nil), "mua.im.relation.UpgradeGroupRsp")
	proto.RegisterType((*GetGroupReq)(nil), "mua.im.relation.GetGroupReq")
	proto.RegisterType((*GetGroupRsp)(nil), "mua.im.relation.GetGroupRsp")
	proto.RegisterType((*ListGroupMemberIDReq)(nil), "mua.im.relation.ListGroupMemberIDReq")
	proto.RegisterType((*ListGroupMemberIDRsp)(nil), "mua.im.relation.ListGroupMemberIDRsp")
}

func init() { proto.RegisterFile("mua/im_relation.proto", fileDescriptor_77be588edaa88f80) }

var fileDescriptor_77be588edaa88f80 = []byte{
	// 1090 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcd, 0x6e, 0xdb, 0xc6,
	0x13, 0x0f, 0x49, 0xd3, 0x16, 0x47, 0xb2, 0x4d, 0x4f, 0xfc, 0x77, 0xf8, 0x67, 0xdc, 0x46, 0x65,
	0x11, 0x44, 0xf0, 0x41, 0x01, 0x5c, 0x14, 0x45, 0xd2, 0xb8, 0x88, 0x63, 0xc3, 0x8e, 0x8a, 0xa6,
	0x6e, 0xe9, 0xe8, 0xd2, 0x1e, 0x1a, 0x5a, 0x5c, 0x2b, 0x8c, 0x25, 0x72, 0xcb, 0xa5, 0x60, 0xb8,
	0xef, 0xd0, 0x43, 0x2f, 0x7d, 0x82, 0x3e, 0x40, 0x1f, 0xb1, 0xd8, 0x5d, 0x92, 0xa2, 0x44, 0xea,
	0xc3, 0x3a, 0x69, 0x67, 0x67, 0xe6, 0x37, 0xb3, 0xf3, 0x49, 0xc1, 0xff, 0x86, 0x23, 0xef, 0x79,
	0x30, 0xfc, 0x2d, 0x26, 0x03, 0x2f, 0x09, 0xa2, 0xb0, 0x4d, 0xe3, 0x28, 0x89, 0x70, 0x7b, 0x38,
	0xf2, 0xda, 0xc1, 0xb0, 0x9d, 0x5d, 0x3b, 0x7f, 0x29, 0xa0, 0x9f, 0xc7, 0xd1, 0x88, 0xe2, 0x16,
	0xa8, 0x9d, 0x53, 0x4b, 0x69, 0x2a, 0x2d, 0xcd, 0x55, 0x3b, 0xa7, 0x88, 0xb0, 0x16, 0x7a, 0x43,
	0x62, 0xa9, 0x4d, 0xa5, 0x65, 0xb8, 0xe2, 0x8c, 0x7b, 0xb0, 0x1e, 0x46, 0x49, 0xd0, 0x23, 0x96,
	0x26, 0x6e, 0x53, 0x0a, 0xf7, 0xc1, 0xe8, 0xc5, 0xc4, 0x4b, 0x88, 0x7f, 0x9c, 0x58, 0x6b, 0x02,
	0x62, 0x7c, 0x81, 0x6d, 0x58, 0x4b, 0xee, 0x28, 0xb1, 0xf4, 0xa6, 0xd2, 0xda, 0x3a, 0xb4, 0xdb,
	0x53, 0x3e, 0xb4, 0x85, 0xfd, 0xf7, 0x77, 0x94, 0xb8, 0x42, 0xce, 0xf9, 0x47, 0x05, 0xf3, 0x27,
	0x12, 0xb3, 0x28, 0xf4, 0x06, 0x6e, 0x2a, 0xc4, 0x4d, 0xb3, 0xb8, 0xd7, 0xed, 0x9c, 0x0a, 0x87,
	0x34, 0x37, 0xa5, 0xf8, 0xbd, 0xcf, 0x12, 0x7e, 0xaf, 0xc9, 0x7b, 0x49, 0xa1, 0x0d, 0xb5, 0x80,
	0x9d, 0x45, 0x83, 0x41, 0x74, 0x2b, 0x3c, 0xaa, 0xb9, 0x39, 0x9d, 0xf2, 0xe2, 0x80, 0x84, 0xbe,
	0x70, 0x4a, 0xf2, 0x04, 0x8d, 0x16, 0x6c, 0x04, 0xec, 0xcd, 0x20, 0xea, 0xdd, 0x58, 0xeb, 0x82,
	0x95, 0x91, 0xdc, 0x52, 0x4c, 0x86, 0x5e, 0x7c, 0x63, 0x6d, 0xc8, 0xc7, 0x4b, 0x0a, 0x4d, 0xd0,
	0x12, 0xaf, 0x6f, 0xd5, 0x9a, 0x5a, 0xcb, 0x70, 0xf9, 0x91, 0x87, 0xce, 0x27, 0xac, 0x67, 0x19,
	0x32, 0x74, 0xfc, 0xcc, 0x6d, 0x5e, 0x0b, 0xeb, 0xc7, 0x89, 0x05, 0xc2, 0xd3, 0x9c, 0x16, 0x3c,
	0x61, 0xfd, 0x38, 0xb1, 0xea, 0x29, 0x2f, 0xa5, 0xb9, 0x3f, 0x57, 0xdc, 0xfc, 0x71, 0x62, 0x35,
	0x04, 0x2b, 0x23, 0x9d, 0x3f, 0x15, 0xd8, 0x14, 0xa1, 0x5b, 0x18, 0x23, 0x0b, 0x36, 0xfa, 0x5c,
	0x30, 0x0f, 0x52, 0x46, 0x72, 0x8d, 0x4f, 0x51, 0x10, 0xe6, 0x59, 0x4b, 0x29, 0x3c, 0x84, 0xb5,
	0x38, 0x1a, 0x64, 0x29, 0xfb, 0xbc, 0x3a, 0x65, 0x6e, 0x34, 0x20, 0x32, 0x6d, 0x5c, 0xd6, 0xf9,
	0x16, 0x0c, 0x19, 0x5f, 0x97, 0xfc, 0x5e, 0x70, 0x45, 0x99, 0x91, 0x2e, 0xb5, 0x98, 0x2e, 0xa7,
	0x9e, 0x2b, 0x33, 0xea, 0x1c, 0x41, 0xbd, 0x1b, 0x5e, 0xaf, 0x8c, 0xb5, 0x59, 0x50, 0x67, 0xd4,
	0x79, 0x09, 0x35, 0x91, 0xc0, 0x55, 0xa0, 0x20, 0xd3, 0x65, 0xd4, 0x79, 0x05, 0xd0, 0x0d, 0xaf,
	0x56, 0x45, 0x6a, 0x8c, 0xb5, 0x19, 0x75, 0xde, 0xc2, 0xde, 0x39, 0x49, 0xa6, 0x8b, 0x7c, 0x15,
	0xdc, 0x8b, 0x6a, 0x24, 0x46, 0xf1, 0x6b, 0x58, 0x0b, 0xc2, 0xeb, 0x48, 0xe0, 0xd4, 0x0f, 0xbf,
	0x28, 0xe5, 0xb0, 0xa4, 0x23, 0xc4, 0x9d, 0xbf, 0x15, 0x78, 0xf4, 0x43, 0xc0, 0x2a, 0x9d, 0x33,
	0x41, 0x1b, 0x7b, 0xc6, 0x8f, 0xf8, 0x22, 0xed, 0x6d, 0x55, 0x14, 0xca, 0xd3, 0x85, 0x46, 0xc6,
	0x6d, 0xce, 0xbb, 0x84, 0x7a, 0x7d, 0x39, 0x4a, 0x74, 0x57, 0x9c, 0x79, 0x27, 0xf0, 0xdf, 0xcb,
	0xe0, 0x0f, 0x22, 0x2a, 0x52, 0x77, 0x73, 0xda, 0xf9, 0x38, 0xc3, 0x2f, 0x46, 0xf1, 0x1b, 0xd0,
	0xb9, 0xef, 0xcc, 0x52, 0x9a, 0xda, 0x72, 0x6f, 0x95, 0xf2, 0xb8, 0x0b, 0x7a, 0x12, 0x25, 0xde,
	0x40, 0xf8, 0xaf, 0xbb, 0x92, 0x70, 0x5e, 0x42, 0xe3, 0xfb, 0x28, 0x08, 0xd3, 0xe6, 0xaa, 0x7a,
	0x76, 0xa1, 0xa3, 0xd4, 0x89, 0x8e, 0x72, 0x9c, 0xa2, 0x2e, 0xa3, 0xfc, 0x95, 0xbd, 0xc8, 0x27,
	0x42, 0x59, 0x77, 0xc5, 0x99, 0xe3, 0xff, 0x3c, 0x0a, 0x92, 0x95, 0xf0, 0xb7, 0x8a, 0xba, 0x8c,
	0x3a, 0x67, 0xb0, 0x75, 0x22, 0x26, 0x6d, 0x8e, 0x36, 0xab, 0x82, 0xf6, 0xc1, 0x10, 0x20, 0x3f,
	0x8e, 0xa7, 0xfa, 0xf8, 0xc2, 0x79, 0x35, 0x89, 0xc3, 0x28, 0x1e, 0x4c, 0xd4, 0xcf, 0xde, 0x8c,
	0x19, 0x20, 0x8b, 0xc6, 0x05, 0x3c, 0xf9, 0xe8, 0x85, 0x7d, 0xa9, 0xdd, 0x09, 0xaf, 0xa3, 0xf4,
	0x5d, 0xa3, 0xc0, 0xcf, 0xde, 0x35, 0x0a, 0xfc, 0x1c, 0x53, 0x5d, 0x02, 0xf3, 0x75, 0x19, 0xf3,
	0x9e, 0x5e, 0x0d, 0x61, 0xbb, 0x4b, 0xfb, 0xb1, 0xe7, 0x8f, 0x83, 0x53, 0x08, 0xac, 0x32, 0x39,
	0x0a, 0xdb, 0x13, 0x95, 0xbc, 0x70, 0x4b, 0x65, 0x8f, 0xd3, 0xf2, 0xc7, 0x39, 0x47, 0x53, 0xe6,
	0xee, 0xe9, 0xed, 0x33, 0xa8, 0x9f, 0x93, 0x64, 0xb1, 0xa7, 0xce, 0x8b, 0x82, 0xe0, 0x3d, 0x6d,
	0x7c, 0x80, 0x5d, 0xde, 0x43, 0xe2, 0xea, 0x1d, 0x19, 0x5e, 0x91, 0xb8, 0x73, 0x3a, 0x3f, 0x2c,
	0x59, 0x97, 0xaa, 0x33, 0xba, 0x54, 0x9b, 0xea, 0xd2, 0xef, 0xaa, 0x2c, 0x30, 0x3a, 0xae, 0x05,
	0x2d, 0xab, 0x85, 0xca, 0xde, 0x3b, 0x78, 0x0b, 0x46, 0x1e, 0x69, 0xdc, 0x05, 0x33, 0x27, 0xba,
	0xe1, 0x4d, 0x18, 0xdd, 0x86, 0xe6, 0x03, 0xdc, 0x04, 0xe3, 0x3d, 0x19, 0xd2, 0x28, 0xf6, 0xe2,
	0x3b, 0x53, 0xc1, 0x3a, 0x6c, 0x9c, 0x93, 0x90, 0xc4, 0xde, 0xc0, 0x54, 0xd1, 0x00, 0xfd, 0x72,
	0x44, 0x49, 0x6c, 0x6a, 0x07, 0x97, 0xd9, 0x7a, 0x4c, 0xd7, 0x14, 0x3e, 0x82, 0x87, 0x13, 0x17,
	0x12, 0xd1, 0x7c, 0x80, 0x3b, 0xb0, 0x99, 0x22, 0x48, 0x8f, 0x4d, 0x85, 0xe3, 0x5c, 0xdc, 0x86,
	0x24, 0x36, 0x55, 0x8e, 0xff, 0xce, 0x0b, 0xbd, 0xbe, 0x00, 0xfd, 0x00, 0xbb, 0x55, 0x23, 0x0d,
	0x9f, 0xc0, 0xe3, 0xaa, 0xfb, 0xb1, 0xd3, 0x0d, 0xa8, 0xc9, 0x05, 0x47, 0x7c, 0x53, 0x11, 0x94,
	0xd8, 0xf0, 0xc4, 0x97, 0x16, 0xc4, 0x96, 0x21, 0xbe, 0xa9, 0x1d, 0xfe, 0x5b, 0x83, 0x5a, 0xbe,
	0xd1, 0x5f, 0xc3, 0x7a, 0xf6, 0xcd, 0x52, 0xca, 0x6b, 0xbe, 0x6c, 0xed, 0x99, 0x3c, 0x46, 0xf1,
	0x0c, 0x6a, 0xd9, 0x32, 0xc4, 0xfd, 0x92, 0x5c, 0x61, 0xcd, 0xda, 0x73, 0xb8, 0x8c, 0xe2, 0x11,
	0xe8, 0xf2, 0x33, 0xe8, 0xff, 0x25, 0xb1, 0x6c, 0xbb, 0xda, 0xb3, 0x58, 0x8c, 0xe2, 0x09, 0x6c,
	0xa4, 0xeb, 0x0f, 0x1f, 0x57, 0xd8, 0xc9, 0xd6, 0xaa, 0x3d, 0x9b, 0xc9, 0x28, 0xf6, 0xe1, 0x61,
	0xc5, 0xae, 0xc3, 0x67, 0xe5, 0x92, 0xaf, 0xdc, 0xad, 0xf6, 0x72, 0x82, 0x8c, 0xe2, 0x27, 0x59,
	0xc4, 0x25, 0x4b, 0xad, 0x12, 0xc0, 0x8c, 0x4d, 0x69, 0x2f, 0x29, 0xc9, 0x28, 0x5e, 0x40, 0xbd,
	0x30, 0x78, 0xf1, 0x49, 0x49, 0x71, 0x72, 0xbc, 0xdb, 0xf3, 0x05, 0x64, 0xc6, 0xb3, 0xf1, 0x50,
	0x91, 0xf1, 0xc2, 0x88, 0xb1, 0xe7, 0x70, 0x19, 0x45, 0x0f, 0x76, 0x4a, 0x9d, 0x8c, 0x4f, 0x2b,
	0xdf, 0x35, 0x3d, 0x4f, 0xec, 0x65, 0xc4, 0x18, 0xc5, 0x5f, 0x61, 0x7b, 0x6a, 0xc4, 0xe3, 0x97,
	0xe5, 0xe7, 0x95, 0x16, 0x8b, 0xbd, 0x58, 0x88, 0x51, 0x74, 0xa1, 0x51, 0x1c, 0xc7, 0xd8, 0x2c,
	0x97, 0xd6, 0xe4, 0x72, 0xb0, 0x17, 0x48, 0x30, 0x8a, 0x1d, 0x30, 0xf2, 0xed, 0x8e, 0x9f, 0x95,
	0xc4, 0x8b, 0x5f, 0x0d, 0xf6, 0x3c, 0xb6, 0x84, 0xca, 0x17, 0x79, 0x05, 0x54, 0xf1, 0x03, 0xc1,
	0x9e, 0xc7, 0x66, 0xf4, 0xcd, 0xce, 0x2f, 0xdb, 0xf2, 0xef, 0xde, 0xf3, 0x8c, 0x7f, 0xb5, 0x2e,
	0xfe, 0xef, 0x7d, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x6c, 0x6b, 0xb2, 0x08, 0x0e,
	0x00, 0x00,
}
