// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mua/im_logic.proto

package logic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	im "github.com/tinyhole/im/idl/mua/im"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushMsgReq struct {
	Msg                  *im.Msg  `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{0}
}

func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (m *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(m, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetMsg() *im.Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type PushMsgRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgRsp) Reset()         { *m = PushMsgRsp{} }
func (m *PushMsgRsp) String() string { return proto.CompactTextString(m) }
func (*PushMsgRsp) ProtoMessage()    {}
func (*PushMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{1}
}

func (m *PushMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgRsp.Unmarshal(m, b)
}
func (m *PushMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgRsp.Marshal(b, m, deterministic)
}
func (m *PushMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgRsp.Merge(m, src)
}
func (m *PushMsgRsp) XXX_Size() int {
	return xxx_messageInfo_PushMsgRsp.Size(m)
}
func (m *PushMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgRsp proto.InternalMessageInfo

type SignInReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ApID                 int32    `protobuf:"varint,3,opt,name=apID,proto3" json:"apID,omitempty"`
	ApFid                int64    `protobuf:"varint,4,opt,name=apFid,proto3" json:"apFid,omitempty"`
	RemoteIP             string   `protobuf:"bytes,5,opt,name=remoteIP,proto3" json:"remoteIP,omitempty"`
	DeviceType           int32    `protobuf:"varint,6,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	SrvName              string   `protobuf:"bytes,7,opt,name=srvName,proto3" json:"srvName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInReq) Reset()         { *m = SignInReq{} }
func (m *SignInReq) String() string { return proto.CompactTextString(m) }
func (*SignInReq) ProtoMessage()    {}
func (*SignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{2}
}

func (m *SignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq.Unmarshal(m, b)
}
func (m *SignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq.Marshal(b, m, deterministic)
}
func (m *SignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq.Merge(m, src)
}
func (m *SignInReq) XXX_Size() int {
	return xxx_messageInfo_SignInReq.Size(m)
}
func (m *SignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq proto.InternalMessageInfo

func (m *SignInReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SignInReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SignInReq) GetApID() int32 {
	if m != nil {
		return m.ApID
	}
	return 0
}

func (m *SignInReq) GetApFid() int64 {
	if m != nil {
		return m.ApFid
	}
	return 0
}

func (m *SignInReq) GetRemoteIP() string {
	if m != nil {
		return m.RemoteIP
	}
	return ""
}

func (m *SignInReq) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *SignInReq) GetSrvName() string {
	if m != nil {
		return m.SrvName
	}
	return ""
}

type SignInRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRsp) Reset()         { *m = SignInRsp{} }
func (m *SignInRsp) String() string { return proto.CompactTextString(m) }
func (*SignInRsp) ProtoMessage()    {}
func (*SignInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{3}
}

func (m *SignInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRsp.Unmarshal(m, b)
}
func (m *SignInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRsp.Marshal(b, m, deterministic)
}
func (m *SignInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRsp.Merge(m, src)
}
func (m *SignInRsp) XXX_Size() int {
	return xxx_messageInfo_SignInRsp.Size(m)
}
func (m *SignInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRsp proto.InternalMessageInfo

type PingReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ApID                 int32    `protobuf:"varint,2,opt,name=apID,proto3" json:"apID,omitempty"`
	ApFid                int64    `protobuf:"varint,3,opt,name=apFid,proto3" json:"apFid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{4}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PingReq) GetApID() int32 {
	if m != nil {
		return m.ApID
	}
	return 0
}

func (m *PingReq) GetApFid() int64 {
	if m != nil {
		return m.ApFid
	}
	return 0
}

type PingRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRsp) Reset()         { *m = PingRsp{} }
func (m *PingRsp) String() string { return proto.CompactTextString(m) }
func (*PingRsp) ProtoMessage()    {}
func (*PingRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{5}
}

func (m *PingRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRsp.Unmarshal(m, b)
}
func (m *PingRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRsp.Marshal(b, m, deterministic)
}
func (m *PingRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRsp.Merge(m, src)
}
func (m *PingRsp) XXX_Size() int {
	return xxx_messageInfo_PingRsp.Size(m)
}
func (m *PingRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PingRsp proto.InternalMessageInfo

type SessionInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Fid                  int64    `protobuf:"varint,2,opt,name=fid,proto3" json:"fid,omitempty"`
	ApName               string   `protobuf:"bytes,3,opt,name=apName,proto3" json:"apName,omitempty"`
	ApID                 int32    `protobuf:"varint,4,opt,name=apID,proto3" json:"apID,omitempty"`
	DeviceType           int32    `protobuf:"varint,5,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionInfo) Reset()         { *m = SessionInfo{} }
func (m *SessionInfo) String() string { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()    {}
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{6}
}

func (m *SessionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionInfo.Unmarshal(m, b)
}
func (m *SessionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionInfo.Marshal(b, m, deterministic)
}
func (m *SessionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionInfo.Merge(m, src)
}
func (m *SessionInfo) XXX_Size() int {
	return xxx_messageInfo_SessionInfo.Size(m)
}
func (m *SessionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SessionInfo proto.InternalMessageInfo

func (m *SessionInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SessionInfo) GetFid() int64 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *SessionInfo) GetApName() string {
	if m != nil {
		return m.ApName
	}
	return ""
}

func (m *SessionInfo) GetApID() int32 {
	if m != nil {
		return m.ApID
	}
	return 0
}

func (m *SessionInfo) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

type ListSessionInfoReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSessionInfoReq) Reset()         { *m = ListSessionInfoReq{} }
func (m *ListSessionInfoReq) String() string { return proto.CompactTextString(m) }
func (*ListSessionInfoReq) ProtoMessage()    {}
func (*ListSessionInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{7}
}

func (m *ListSessionInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionInfoReq.Unmarshal(m, b)
}
func (m *ListSessionInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionInfoReq.Marshal(b, m, deterministic)
}
func (m *ListSessionInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionInfoReq.Merge(m, src)
}
func (m *ListSessionInfoReq) XXX_Size() int {
	return xxx_messageInfo_ListSessionInfoReq.Size(m)
}
func (m *ListSessionInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionInfoReq proto.InternalMessageInfo

func (m *ListSessionInfoReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type ListSessionInfoRsp struct {
	Infos                []*SessionInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListSessionInfoRsp) Reset()         { *m = ListSessionInfoRsp{} }
func (m *ListSessionInfoRsp) String() string { return proto.CompactTextString(m) }
func (*ListSessionInfoRsp) ProtoMessage()    {}
func (*ListSessionInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{8}
}

func (m *ListSessionInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionInfoRsp.Unmarshal(m, b)
}
func (m *ListSessionInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionInfoRsp.Marshal(b, m, deterministic)
}
func (m *ListSessionInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionInfoRsp.Merge(m, src)
}
func (m *ListSessionInfoRsp) XXX_Size() int {
	return xxx_messageInfo_ListSessionInfoRsp.Size(m)
}
func (m *ListSessionInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionInfoRsp proto.InternalMessageInfo

func (m *ListSessionInfoRsp) GetInfos() []*SessionInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type BatchListSessionInfoReq struct {
	Uids                 []int64  `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchListSessionInfoReq) Reset()         { *m = BatchListSessionInfoReq{} }
func (m *BatchListSessionInfoReq) String() string { return proto.CompactTextString(m) }
func (*BatchListSessionInfoReq) ProtoMessage()    {}
func (*BatchListSessionInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{9}
}

func (m *BatchListSessionInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchListSessionInfoReq.Unmarshal(m, b)
}
func (m *BatchListSessionInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchListSessionInfoReq.Marshal(b, m, deterministic)
}
func (m *BatchListSessionInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchListSessionInfoReq.Merge(m, src)
}
func (m *BatchListSessionInfoReq) XXX_Size() int {
	return xxx_messageInfo_BatchListSessionInfoReq.Size(m)
}
func (m *BatchListSessionInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchListSessionInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_BatchListSessionInfoReq proto.InternalMessageInfo

func (m *BatchListSessionInfoReq) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

type BatchListSessionInfoRsp struct {
	Infos                []*SessionInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BatchListSessionInfoRsp) Reset()         { *m = BatchListSessionInfoRsp{} }
func (m *BatchListSessionInfoRsp) String() string { return proto.CompactTextString(m) }
func (*BatchListSessionInfoRsp) ProtoMessage()    {}
func (*BatchListSessionInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_af83ad25a3e67790, []int{10}
}

func (m *BatchListSessionInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchListSessionInfoRsp.Unmarshal(m, b)
}
func (m *BatchListSessionInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchListSessionInfoRsp.Marshal(b, m, deterministic)
}
func (m *BatchListSessionInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchListSessionInfoRsp.Merge(m, src)
}
func (m *BatchListSessionInfoRsp) XXX_Size() int {
	return xxx_messageInfo_BatchListSessionInfoRsp.Size(m)
}
func (m *BatchListSessionInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchListSessionInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BatchListSessionInfoRsp proto.InternalMessageInfo

func (m *BatchListSessionInfoRsp) GetInfos() []*SessionInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*PushMsgReq)(nil), "mua.im.logic.PushMsgReq")
	proto.RegisterType((*PushMsgRsp)(nil), "mua.im.logic.PushMsgRsp")
	proto.RegisterType((*SignInReq)(nil), "mua.im.logic.SignInReq")
	proto.RegisterType((*SignInRsp)(nil), "mua.im.logic.SignInRsp")
	proto.RegisterType((*PingReq)(nil), "mua.im.logic.PingReq")
	proto.RegisterType((*PingRsp)(nil), "mua.im.logic.PingRsp")
	proto.RegisterType((*SessionInfo)(nil), "mua.im.logic.SessionInfo")
	proto.RegisterType((*ListSessionInfoReq)(nil), "mua.im.logic.ListSessionInfoReq")
	proto.RegisterType((*ListSessionInfoRsp)(nil), "mua.im.logic.ListSessionInfoRsp")
	proto.RegisterType((*BatchListSessionInfoReq)(nil), "mua.im.logic.BatchListSessionInfoReq")
	proto.RegisterType((*BatchListSessionInfoRsp)(nil), "mua.im.logic.BatchListSessionInfoRsp")
}

func init() { proto.RegisterFile("mua/im_logic.proto", fileDescriptor_af83ad25a3e67790) }

var fileDescriptor_af83ad25a3e67790 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0x26, 0x9d, 0xa4, 0xb5, 0x2f, 0x45, 0x97, 0xe7, 0xea, 0x8e, 0x01, 0x25, 0x0c, 0x28, 0x05,
	0x31, 0x85, 0xea, 0x49, 0xf0, 0xb2, 0xb8, 0x42, 0x65, 0x95, 0x92, 0xd5, 0x8b, 0x17, 0x89, 0xcd,
	0x34, 0x3b, 0xe8, 0x64, 0xc6, 0x4e, 0xb2, 0xe0, 0xc1, 0xbf, 0xca, 0xbf, 0xcd, 0xbb, 0x64, 0x92,
	0x76, 0xd3, 0x6c, 0x8a, 0xe2, 0xed, 0xfd, 0xf8, 0xbe, 0xef, 0x7d, 0x33, 0xf3, 0x18, 0x40, 0x59,
	0x26, 0x33, 0x21, 0x3f, 0x7f, 0x53, 0x99, 0x58, 0x45, 0x7a, 0xa3, 0x0a, 0x85, 0x13, 0x59, 0x26,
	0x91, 0x90, 0x91, 0xad, 0x05, 0x77, 0x1b, 0xc4, 0x4a, 0x49, 0xa9, 0xf2, 0x1a, 0xc2, 0x9e, 0x02,
	0x2c, 0x4b, 0x73, 0xf9, 0xce, 0x64, 0x31, 0xff, 0x8e, 0x0f, 0x81, 0x48, 0x93, 0x51, 0x27, 0x74,
	0xa6, 0xfe, 0xdc, 0x8f, 0x1a, 0x7a, 0xd5, 0xac, 0xea, 0x6c, 0x72, 0x0d, 0x36, 0x9a, 0xfd, 0x72,
	0x60, 0x7c, 0x21, 0xb2, 0x7c, 0x91, 0x57, 0xd4, 0x23, 0x20, 0xa5, 0x48, 0x2d, 0x95, 0xc4, 0x55,
	0x88, 0xc7, 0xe0, 0x15, 0xea, 0x2b, 0xcf, 0xe9, 0x20, 0x74, 0xa6, 0xe3, 0xb8, 0x4e, 0x10, 0xc1,
	0x4d, 0xf4, 0xe2, 0x35, 0x25, 0xa1, 0x33, 0xf5, 0x62, 0x1b, 0x57, 0xc8, 0x44, 0xbf, 0x11, 0x29,
	0x75, 0x2d, 0xbb, 0x4e, 0x30, 0x80, 0x5b, 0x1b, 0x2e, 0x55, 0xc1, 0x17, 0x4b, 0xea, 0x59, 0x89,
	0x5d, 0x8e, 0x8f, 0x00, 0x52, 0x7e, 0x25, 0x56, 0xfc, 0xc3, 0x0f, 0xcd, 0xe9, 0xd0, 0x6a, 0xb5,
	0x2a, 0x48, 0x61, 0x64, 0x36, 0x57, 0xef, 0x13, 0xc9, 0xe9, 0xc8, 0x52, 0xb7, 0x29, 0xf3, 0x77,
	0xa6, 0x8d, 0x66, 0x67, 0x30, 0x5a, 0x8a, 0x3c, 0xeb, 0xf7, 0xbf, 0x75, 0x3a, 0xe8, 0x73, 0x4a,
	0x5a, 0x4e, 0xd9, 0xb8, 0x91, 0x31, 0x9a, 0xfd, 0x04, 0xff, 0x82, 0x1b, 0x23, 0x54, 0xbe, 0xc8,
	0xd7, 0xaa, 0x47, 0xf5, 0x08, 0xc8, 0x5a, 0xa4, 0x56, 0x94, 0xc4, 0x55, 0x88, 0xf7, 0x61, 0x98,
	0x68, 0x6b, 0x95, 0x58, 0xab, 0x4d, 0xb6, 0x9b, 0xef, 0xb6, 0xe6, 0xef, 0x9f, 0xdb, 0xeb, 0x9e,
	0x9b, 0x3d, 0x01, 0x3c, 0x17, 0xa6, 0x68, 0x59, 0xe8, 0x3d, 0x1b, 0x3b, 0xbb, 0x89, 0x33, 0x1a,
	0x67, 0xe0, 0x89, 0x7c, 0xad, 0x0c, 0x75, 0x42, 0x32, 0xf5, 0xe7, 0x0f, 0xa2, 0xf6, 0xfe, 0x44,
	0x6d, 0x70, 0x8d, 0x63, 0xcf, 0xe0, 0xe4, 0x34, 0x29, 0x56, 0x97, 0x3d, 0x33, 0x11, 0xdc, 0x52,
	0xa4, 0xb5, 0x14, 0x89, 0x6d, 0xcc, 0xde, 0x1e, 0x80, 0xff, 0xc7, 0xe8, 0xf9, 0xef, 0x01, 0x78,
	0xe7, 0x55, 0x13, 0x5f, 0xc1, 0xa8, 0xd9, 0x4a, 0xa4, 0xfb, 0xb4, 0xeb, 0xcd, 0x0e, 0x0e, 0x74,
	0x8c, 0xc6, 0x97, 0x30, 0xac, 0x17, 0x02, 0x4f, 0x3a, 0x43, 0xb7, 0xbb, 0x1d, 0xf4, 0x37, 0x8c,
	0xc6, 0x17, 0xe0, 0x56, 0x0f, 0x8f, 0xf7, 0x3a, 0xea, 0xf5, 0x4e, 0x05, 0x7d, 0x65, 0xa3, 0xf1,
	0x23, 0xdc, 0xe9, 0xdc, 0x00, 0x86, 0xfb, 0xc8, 0x9b, 0xf7, 0x19, 0xfc, 0x05, 0x61, 0x34, 0xa6,
	0x70, 0xdc, 0x77, 0xbb, 0xf8, 0x78, 0x9f, 0x79, 0xe0, 0xc1, 0x82, 0x7f, 0x81, 0x19, 0x7d, 0x7a,
	0xfb, 0xd3, 0xa4, 0xfe, 0x47, 0x66, 0x16, 0xf7, 0x65, 0x68, 0xff, 0x91, 0xe7, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xf3, 0xd3, 0x71, 0xb5, 0x80, 0x04, 0x00, 0x00,
}
