// Code generated by protoc-gen-go. DO NOT EDIT.
// source: package.proto

package pack

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallType int32

const (
	CallType_CallTypeUnknown CallType = 0
	CallType_Sync            CallType = 1
	CallType_Async           CallType = 2
	CallType_Push            CallType = 3
)

var CallType_name = map[int32]string{
	0: "CallTypeUnknown",
	1: "Sync",
	2: "Async",
	3: "Push",
}

var CallType_value = map[string]int32{
	"CallTypeUnknown": 0,
	"Sync":            1,
	"Async":           2,
	"Push":            3,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}

func (CallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae8103ff0e06fb71, []int{0}
}

type DeviceType int32

const (
	DeviceType_DeviceTypeUnknown DeviceType = 0
	DeviceType_PCLinux           DeviceType = 1
	DeviceType_PCWindows         DeviceType = 2
	DeviceType_PhoneAndroid      DeviceType = 3
	DeviceType_PhoneIOS          DeviceType = 4
	DeviceType_PadAndroid        DeviceType = 5
	DeviceType_PadIOS            DeviceType = 6
)

var DeviceType_name = map[int32]string{
	0: "DeviceTypeUnknown",
	1: "PCLinux",
	2: "PCWindows",
	3: "PhoneAndroid",
	4: "PhoneIOS",
	5: "PadAndroid",
	6: "PadIOS",
}

var DeviceType_value = map[string]int32{
	"DeviceTypeUnknown": 0,
	"PCLinux":           1,
	"PCWindows":         2,
	"PhoneAndroid":      3,
	"PhoneIOS":          4,
	"PadAndroid":        5,
	"PadIOS":            6,
}

func (x DeviceType) String() string {
	return proto.EnumName(DeviceType_name, int32(x))
}

func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae8103ff0e06fb71, []int{1}
}

type RequestMeta struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Endpoint             string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	CallType             CallType `protobuf:"varint,3,opt,name=callType,proto3,enum=pack.CallType" json:"callType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMeta) Reset()         { *m = RequestMeta{} }
func (m *RequestMeta) String() string { return proto.CompactTextString(m) }
func (*RequestMeta) ProtoMessage()    {}
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8103ff0e06fb71, []int{0}
}

func (m *RequestMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMeta.Unmarshal(m, b)
}
func (m *RequestMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMeta.Marshal(b, m, deterministic)
}
func (m *RequestMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMeta.Merge(m, src)
}
func (m *RequestMeta) XXX_Size() int {
	return xxx_messageInfo_RequestMeta.Size(m)
}
func (m *RequestMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMeta proto.InternalMessageInfo

func (m *RequestMeta) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *RequestMeta) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *RequestMeta) GetCallType() CallType {
	if m != nil {
		return m.CallType
	}
	return CallType_CallTypeUnknown
}

type ResponseMeta struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrText              string   `protobuf:"bytes,2,opt,name=errText,proto3" json:"errText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseMeta) Reset()         { *m = ResponseMeta{} }
func (m *ResponseMeta) String() string { return proto.CompactTextString(m) }
func (*ResponseMeta) ProtoMessage()    {}
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8103ff0e06fb71, []int{1}
}

func (m *ResponseMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMeta.Unmarshal(m, b)
}
func (m *ResponseMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMeta.Marshal(b, m, deterministic)
}
func (m *ResponseMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMeta.Merge(m, src)
}
func (m *ResponseMeta) XXX_Size() int {
	return xxx_messageInfo_ResponseMeta.Size(m)
}
func (m *ResponseMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMeta proto.InternalMessageInfo

func (m *ResponseMeta) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ResponseMeta) GetErrText() string {
	if m != nil {
		return m.ErrText
	}
	return ""
}

type Device struct {
	Guid                 string     `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Type                 DeviceType `protobuf:"varint,2,opt,name=type,proto3,enum=pack.DeviceType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8103ff0e06fb71, []int{2}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Device) GetType() DeviceType {
	if m != nil {
		return m.Type
	}
	return DeviceType_DeviceTypeUnknown
}

type AuthInfo struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthInfo) Reset()         { *m = AuthInfo{} }
func (m *AuthInfo) String() string { return proto.CompactTextString(m) }
func (*AuthInfo) ProtoMessage()    {}
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8103ff0e06fb71, []int{3}
}

func (m *AuthInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthInfo.Unmarshal(m, b)
}
func (m *AuthInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthInfo.Marshal(b, m, deterministic)
}
func (m *AuthInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthInfo.Merge(m, src)
}
func (m *AuthInfo) XXX_Size() int {
	return xxx_messageInfo_AuthInfo.Size(m)
}
func (m *AuthInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthInfo proto.InternalMessageInfo

func (m *AuthInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AuthInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Header struct {
	Request              *RequestMeta  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response             *ResponseMeta `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Seq                  int64         `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Device               *Device       `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Auth                 *AuthInfo     `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae8103ff0e06fb71, []int{4}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetRequest() *RequestMeta {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Header) GetResponse() *ResponseMeta {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Header) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Header) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *Header) GetAuth() *AuthInfo {
	if m != nil {
		return m.Auth
	}
	return nil
}

func init() {
	proto.RegisterEnum("pack.CallType", CallType_name, CallType_value)
	proto.RegisterEnum("pack.DeviceType", DeviceType_name, DeviceType_value)
	proto.RegisterType((*RequestMeta)(nil), "pack.RequestMeta")
	proto.RegisterType((*ResponseMeta)(nil), "pack.ResponseMeta")
	proto.RegisterType((*Device)(nil), "pack.Device")
	proto.RegisterType((*AuthInfo)(nil), "pack.AuthInfo")
	proto.RegisterType((*Header)(nil), "pack.Header")
}

func init() { proto.RegisterFile("package.proto", fileDescriptor_ae8103ff0e06fb71) }

var fileDescriptor_ae8103ff0e06fb71 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x52, 0xcb, 0x6e, 0xdb, 0x30,
	0x10, 0xac, 0xac, 0x87, 0xe5, 0x95, 0xe3, 0x32, 0xdb, 0x16, 0x10, 0x7a, 0x32, 0x84, 0x1c, 0x02,
	0x17, 0xf0, 0xc1, 0xbd, 0x17, 0xb0, 0xdd, 0x43, 0x03, 0xf4, 0x21, 0x30, 0x29, 0x0a, 0xf4, 0xc6,
	0x9a, 0xdb, 0x58, 0x70, 0x4a, 0x2a, 0x7a, 0xd4, 0x31, 0xfa, 0x75, 0xfd, 0xb3, 0x80, 0x94, 0x68,
	0xfb, 0xb6, 0xb3, 0xb3, 0xe4, 0xcc, 0x0e, 0x09, 0x17, 0xa5, 0xd8, 0xec, 0xc4, 0x3d, 0xcd, 0xcb,
	0x4a, 0x37, 0x1a, 0x03, 0x03, 0xb3, 0x3d, 0x24, 0x9c, 0x1e, 0x5b, 0xaa, 0x9b, 0x2f, 0xd4, 0x08,
	0x9c, 0x42, 0x52, 0x53, 0xf5, 0xb7, 0xd8, 0xd0, 0x57, 0xf1, 0x87, 0x52, 0x6f, 0xea, 0x5d, 0x8f,
	0xf8, 0x79, 0x0b, 0xdf, 0x42, 0x4c, 0x4a, 0x96, 0xba, 0x50, 0x4d, 0x3a, 0xb0, 0xf4, 0x11, 0xe3,
	0x0c, 0xe2, 0x8d, 0x78, 0x78, 0xb8, 0x3b, 0x94, 0x94, 0xfa, 0x53, 0xef, 0x7a, 0xb2, 0x98, 0xcc,
	0x8d, 0xca, 0x7c, 0xdd, 0x77, 0xf9, 0x91, 0xcf, 0x56, 0x30, 0xe6, 0x54, 0x97, 0x5a, 0xd5, 0x64,
	0x95, 0x53, 0x18, 0x52, 0x55, 0xad, 0xb5, 0xec, 0x54, 0x43, 0xee, 0x60, 0xcf, 0xdc, 0xd1, 0x93,
	0x13, 0x74, 0x30, 0x5b, 0x41, 0xf4, 0x91, 0x8c, 0x33, 0x44, 0x08, 0xee, 0xdb, 0x42, 0xf6, 0x86,
	0x6d, 0x8d, 0x57, 0x10, 0x34, 0xc6, 0xc9, 0xc0, 0x3a, 0x61, 0x9d, 0x93, 0x6e, 0xde, 0x7a, 0xb1,
	0x6c, 0xb6, 0x80, 0x78, 0xd9, 0x36, 0xdb, 0x1b, 0xf5, 0x5b, 0x23, 0x03, 0xdf, 0x5d, 0xe2, 0x73,
	0x53, 0xe2, 0x6b, 0x08, 0x1b, 0xbd, 0x23, 0xd5, 0x2b, 0x77, 0x20, 0xfb, 0xef, 0x41, 0xf4, 0x89,
	0x84, 0xa4, 0x0a, 0xdf, 0xc1, 0xb0, 0xea, 0xf2, 0xb3, 0xc7, 0x92, 0xc5, 0x65, 0xa7, 0x73, 0x16,
	0x2a, 0x77, 0x13, 0x38, 0x87, 0xb8, 0xea, 0x77, 0xb6, 0x17, 0x26, 0x0b, 0x74, 0xd3, 0xa7, 0x24,
	0xf8, 0x71, 0xc6, 0xf8, 0xa9, 0xe9, 0xd1, 0x46, 0xe9, 0x73, 0x53, 0xe2, 0x15, 0x44, 0xd2, 0x6e,
	0x90, 0x06, 0xf6, 0xfc, 0xf8, 0x7c, 0x2b, 0xde, 0x73, 0x98, 0x41, 0x20, 0xda, 0x66, 0x9b, 0x86,
	0x76, 0xa6, 0x7f, 0x03, 0xb7, 0x25, 0xb7, 0xdc, 0xec, 0x03, 0xc4, 0xee, 0x55, 0xf0, 0x15, 0xbc,
	0x74, 0xf5, 0x77, 0xb5, 0x53, 0x7a, 0xaf, 0xd8, 0x0b, 0x8c, 0x21, 0xb8, 0x3d, 0xa8, 0x0d, 0xf3,
	0x70, 0x04, 0xe1, 0xb2, 0x36, 0xe5, 0xc0, 0x34, 0xf3, 0xb6, 0xde, 0x32, 0x7f, 0xf6, 0x0f, 0xe0,
	0x94, 0x25, 0xbe, 0x81, 0xcb, 0x13, 0x3a, 0xdd, 0x91, 0xc0, 0x30, 0x5f, 0x7f, 0x2e, 0x54, 0xfb,
	0xc4, 0x3c, 0xbc, 0x80, 0x51, 0xbe, 0xfe, 0x51, 0x28, 0xa9, 0xf7, 0x35, 0x1b, 0x20, 0x83, 0x71,
	0xbe, 0xd5, 0x8a, 0x96, 0x4a, 0x56, 0xba, 0x90, 0xcc, 0xc7, 0x31, 0xc4, 0xb6, 0x73, 0xf3, 0xed,
	0x96, 0x05, 0x38, 0x01, 0xc8, 0x85, 0x74, 0x6c, 0x88, 0x00, 0x51, 0x2e, 0xa4, 0xe1, 0xa2, 0x55,
	0xf4, 0xd3, 0xfe, 0xde, 0x5f, 0x91, 0xfd, 0xca, 0xef, 0x9f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1,
	0xcd, 0x96, 0x3d, 0xdb, 0x02, 0x00, 0x00,
}
