// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mua/im_common.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContentType int32

const (
	ContentType_ContentTypeUnknown  ContentType = 0
	ContentType_ContentTypeText     ContentType = 1
	ContentType_ContentTypeImg      ContentType = 2
	ContentType_ContentTypeVideo    ContentType = 3
	ContentType_ContentTypeAudio    ContentType = 4
	ContentType_ContentTypeLink     ContentType = 5
	ContentType_ContentTypeSite     ContentType = 6
	ContentType_ContentTypeMicroApp ContentType = 7
)

var ContentType_name = map[int32]string{
	0: "ContentTypeUnknown",
	1: "ContentTypeText",
	2: "ContentTypeImg",
	3: "ContentTypeVideo",
	4: "ContentTypeAudio",
	5: "ContentTypeLink",
	6: "ContentTypeSite",
	7: "ContentTypeMicroApp",
}

var ContentType_value = map[string]int32{
	"ContentTypeUnknown":  0,
	"ContentTypeText":     1,
	"ContentTypeImg":      2,
	"ContentTypeVideo":    3,
	"ContentTypeAudio":    4,
	"ContentTypeLink":     5,
	"ContentTypeSite":     6,
	"ContentTypeMicroApp": 7,
}

func (x ContentType) String() string {
	return proto.EnumName(ContentType_name, int32(x))
}

func (ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3abd20124147ffc, []int{0}
}

type MsgType int32

const (
	MsgType_MsgypeUnknown MsgType = 0
	MsgType_MsgTypePrivte MsgType = 1
	MsgType_MsgTypeGroup  MsgType = 2
)

var MsgType_name = map[int32]string{
	0: "MsgypeUnknown",
	1: "MsgTypePrivte",
	2: "MsgTypeGroup",
}

var MsgType_value = map[string]int32{
	"MsgypeUnknown": 0,
	"MsgTypePrivte": 1,
	"MsgTypeGroup":  2,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a3abd20124147ffc, []int{1}
}

type Msg struct {
	MsgID                string      `protobuf:"bytes,1,opt,name=msgID,proto3" json:"msgID,omitempty"`
	SrcID                int64       `protobuf:"varint,2,opt,name=srcID,proto3" json:"srcID,omitempty"`
	DstID                int64       `protobuf:"varint,3,opt,name=dstID,proto3" json:"dstID,omitempty"`
	ContentType          ContentType `protobuf:"varint,4,opt,name=contentType,proto3,enum=mua.im.ContentType" json:"contentType,omitempty"`
	Seq                  int64       `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	Time                 int64       `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	Content              string      `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	MsgType              MsgType     `protobuf:"varint,8,opt,name=MsgType,proto3,enum=mua.im.MsgType" json:"MsgType,omitempty"`
	InboxID              int64       `protobuf:"varint,10,opt,name=inboxID,proto3" json:"inboxID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3abd20124147ffc, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *Msg) GetSrcID() int64 {
	if m != nil {
		return m.SrcID
	}
	return 0
}

func (m *Msg) GetDstID() int64 {
	if m != nil {
		return m.DstID
	}
	return 0
}

func (m *Msg) GetContentType() ContentType {
	if m != nil {
		return m.ContentType
	}
	return ContentType_ContentTypeUnknown
}

func (m *Msg) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Msg) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Msg) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_MsgypeUnknown
}

func (m *Msg) GetInboxID() int64 {
	if m != nil {
		return m.InboxID
	}
	return 0
}

func init() {
	proto.RegisterEnum("mua.im.ContentType", ContentType_name, ContentType_value)
	proto.RegisterEnum("mua.im.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Msg)(nil), "mua.im.Msg")
}

func init() { proto.RegisterFile("mua/im_common.proto", fileDescriptor_a3abd20124147ffc) }

var fileDescriptor_a3abd20124147ffc = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x41, 0x4f, 0xab, 0x40,
	0x14, 0x85, 0x1f, 0xd0, 0x42, 0xdf, 0xed, 0x7b, 0xed, 0xbc, 0x4b, 0xf3, 0x9c, 0x65, 0xe3, 0xaa,
	0x76, 0x81, 0x89, 0xc6, 0x1f, 0x50, 0x25, 0x31, 0x24, 0x92, 0x18, 0xac, 0x2e, 0xdc, 0x98, 0x96,
	0x4e, 0xc8, 0xa4, 0x99, 0x19, 0x84, 0x41, 0xeb, 0xda, 0xdf, 0xe5, 0x7f, 0x33, 0x0c, 0x45, 0xb1,
	0xbb, 0x7b, 0xbe, 0x0b, 0xe7, 0x9c, 0x4c, 0x2e, 0xf8, 0xa2, 0x5a, 0x9d, 0x72, 0xf1, 0x94, 0x2a,
	0x21, 0x94, 0x0c, 0xf2, 0x42, 0x69, 0x85, 0xae, 0xa8, 0x56, 0x01, 0x17, 0xc7, 0xef, 0x36, 0x38,
	0x71, 0x99, 0xe1, 0x04, 0xfa, 0xa2, 0xcc, 0xa2, 0x90, 0x5a, 0x53, 0x6b, 0xf6, 0x3b, 0x69, 0x44,
	0x4d, 0xcb, 0x22, 0x8d, 0x42, 0x6a, 0x4f, 0xad, 0x99, 0x93, 0x34, 0xa2, 0xa6, 0x9b, 0x52, 0x47,
	0x21, 0x75, 0x1a, 0x6a, 0x04, 0x5e, 0xc0, 0x30, 0x55, 0x52, 0x33, 0xa9, 0x97, 0x6f, 0x39, 0xa3,
	0xbd, 0xa9, 0x35, 0x1b, 0x9d, 0xf9, 0x41, 0x93, 0x13, 0x5c, 0x7d, 0xaf, 0x92, 0xee, 0x77, 0x48,
	0xc0, 0x29, 0xd9, 0x33, 0xed, 0x1b, 0xab, 0x7a, 0x44, 0x84, 0x9e, 0xe6, 0x82, 0x51, 0xd7, 0x20,
	0x33, 0x23, 0x05, 0x6f, 0xff, 0x13, 0xf5, 0x4c, 0xc1, 0x56, 0xe2, 0x09, 0x78, 0x71, 0x99, 0x99,
	0xc8, 0x81, 0x89, 0x1c, 0xb7, 0x91, 0x7b, 0x9c, 0xb4, 0xfb, 0xda, 0x84, 0xcb, 0xb5, 0xda, 0x45,
	0x21, 0x05, 0xe3, 0xdd, 0xca, 0xf9, 0x87, 0x05, 0xc3, 0x4e, 0x43, 0xfc, 0x0f, 0xd8, 0x91, 0xf7,
	0x72, 0x2b, 0xd5, 0xab, 0x24, 0xbf, 0xd0, 0x87, 0x71, 0x87, 0x2f, 0xd9, 0x4e, 0x13, 0x0b, 0x11,
	0x46, 0x1d, 0x18, 0x89, 0x8c, 0xd8, 0x38, 0x01, 0xd2, 0x61, 0x0f, 0x7c, 0xc3, 0x14, 0x71, 0x0e,
	0xe8, 0xa2, 0xda, 0x70, 0x45, 0x7a, 0x07, 0xa6, 0x37, 0x5c, 0x6e, 0x49, 0xff, 0x00, 0xde, 0x71,
	0xcd, 0x88, 0x8b, 0x47, 0xe0, 0x77, 0x60, 0xcc, 0xd3, 0x42, 0x2d, 0xf2, 0x9c, 0x78, 0xf3, 0xc5,
	0xd7, 0x23, 0xe0, 0x3f, 0xf8, 0x1b, 0x97, 0xd9, 0x8f, 0xd6, 0x0d, 0xaa, 0xb7, 0xb7, 0x05, 0x7f,
	0xd1, 0x8c, 0x58, 0x48, 0xe0, 0xcf, 0x1e, 0x5d, 0x17, 0xaa, 0xca, 0x89, 0x7d, 0x39, 0x78, 0x74,
	0x9b, 0x3b, 0x59, 0xbb, 0xe6, 0x42, 0xce, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xb4, 0xb3,
	0x01, 0x38, 0x02, 0x00, 0x00,
}
