// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mua/im_job.proto

package job

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	im "github.com/tinyhole/im/idl/mua/im"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PullMsgReq struct {
	InboxID              int64    `protobuf:"varint,1,opt,name=inboxID,proto3" json:"inboxID,omitempty"`
	Seq                  int64    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullMsgReq) Reset()         { *m = PullMsgReq{} }
func (m *PullMsgReq) String() string { return proto.CompactTextString(m) }
func (*PullMsgReq) ProtoMessage()    {}
func (*PullMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d1025130c0524fd, []int{0}
}

func (m *PullMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMsgReq.Unmarshal(m, b)
}
func (m *PullMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMsgReq.Marshal(b, m, deterministic)
}
func (m *PullMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMsgReq.Merge(m, src)
}
func (m *PullMsgReq) XXX_Size() int {
	return xxx_messageInfo_PullMsgReq.Size(m)
}
func (m *PullMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PullMsgReq proto.InternalMessageInfo

func (m *PullMsgReq) GetInboxID() int64 {
	if m != nil {
		return m.InboxID
	}
	return 0
}

func (m *PullMsgReq) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type PullMsgRsp struct {
	Msg                  *im.Msg  `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullMsgRsp) Reset()         { *m = PullMsgRsp{} }
func (m *PullMsgRsp) String() string { return proto.CompactTextString(m) }
func (*PullMsgRsp) ProtoMessage()    {}
func (*PullMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d1025130c0524fd, []int{1}
}

func (m *PullMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullMsgRsp.Unmarshal(m, b)
}
func (m *PullMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullMsgRsp.Marshal(b, m, deterministic)
}
func (m *PullMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullMsgRsp.Merge(m, src)
}
func (m *PullMsgRsp) XXX_Size() int {
	return xxx_messageInfo_PullMsgRsp.Size(m)
}
func (m *PullMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PullMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PullMsgRsp proto.InternalMessageInfo

func (m *PullMsgRsp) GetMsg() *im.Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SyncPrivateInboxMsgReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Seq                  int64    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncPrivateInboxMsgReq) Reset()         { *m = SyncPrivateInboxMsgReq{} }
func (m *SyncPrivateInboxMsgReq) String() string { return proto.CompactTextString(m) }
func (*SyncPrivateInboxMsgReq) ProtoMessage()    {}
func (*SyncPrivateInboxMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d1025130c0524fd, []int{2}
}

func (m *SyncPrivateInboxMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPrivateInboxMsgReq.Unmarshal(m, b)
}
func (m *SyncPrivateInboxMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPrivateInboxMsgReq.Marshal(b, m, deterministic)
}
func (m *SyncPrivateInboxMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPrivateInboxMsgReq.Merge(m, src)
}
func (m *SyncPrivateInboxMsgReq) XXX_Size() int {
	return xxx_messageInfo_SyncPrivateInboxMsgReq.Size(m)
}
func (m *SyncPrivateInboxMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPrivateInboxMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPrivateInboxMsgReq proto.InternalMessageInfo

func (m *SyncPrivateInboxMsgReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SyncPrivateInboxMsgReq) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SyncPrivateInboxMsgReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SyncPrivateInboxMsgReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type SyncPrivateInboxMsgRsp struct {
	Msg                  []*im.Msg `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
	Total                int32     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SyncPrivateInboxMsgRsp) Reset()         { *m = SyncPrivateInboxMsgRsp{} }
func (m *SyncPrivateInboxMsgRsp) String() string { return proto.CompactTextString(m) }
func (*SyncPrivateInboxMsgRsp) ProtoMessage()    {}
func (*SyncPrivateInboxMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d1025130c0524fd, []int{3}
}

func (m *SyncPrivateInboxMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPrivateInboxMsgRsp.Unmarshal(m, b)
}
func (m *SyncPrivateInboxMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPrivateInboxMsgRsp.Marshal(b, m, deterministic)
}
func (m *SyncPrivateInboxMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPrivateInboxMsgRsp.Merge(m, src)
}
func (m *SyncPrivateInboxMsgRsp) XXX_Size() int {
	return xxx_messageInfo_SyncPrivateInboxMsgRsp.Size(m)
}
func (m *SyncPrivateInboxMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPrivateInboxMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPrivateInboxMsgRsp proto.InternalMessageInfo

func (m *SyncPrivateInboxMsgRsp) GetMsg() []*im.Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *SyncPrivateInboxMsgRsp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type SyncPublicInboxMsgReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncPublicInboxMsgReq) Reset()         { *m = SyncPublicInboxMsgReq{} }
func (m *SyncPublicInboxMsgReq) String() string { return proto.CompactTextString(m) }
func (*SyncPublicInboxMsgReq) ProtoMessage()    {}
func (*SyncPublicInboxMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d1025130c0524fd, []int{4}
}

func (m *SyncPublicInboxMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPublicInboxMsgReq.Unmarshal(m, b)
}
func (m *SyncPublicInboxMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPublicInboxMsgReq.Marshal(b, m, deterministic)
}
func (m *SyncPublicInboxMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPublicInboxMsgReq.Merge(m, src)
}
func (m *SyncPublicInboxMsgReq) XXX_Size() int {
	return xxx_messageInfo_SyncPublicInboxMsgReq.Size(m)
}
func (m *SyncPublicInboxMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPublicInboxMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPublicInboxMsgReq proto.InternalMessageInfo

func (m *SyncPublicInboxMsgReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type SyncPublicInboxMsgRsp struct {
	Msg                  []*im.Msg `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SyncPublicInboxMsgRsp) Reset()         { *m = SyncPublicInboxMsgRsp{} }
func (m *SyncPublicInboxMsgRsp) String() string { return proto.CompactTextString(m) }
func (*SyncPublicInboxMsgRsp) ProtoMessage()    {}
func (*SyncPublicInboxMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d1025130c0524fd, []int{5}
}

func (m *SyncPublicInboxMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncPublicInboxMsgRsp.Unmarshal(m, b)
}
func (m *SyncPublicInboxMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncPublicInboxMsgRsp.Marshal(b, m, deterministic)
}
func (m *SyncPublicInboxMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPublicInboxMsgRsp.Merge(m, src)
}
func (m *SyncPublicInboxMsgRsp) XXX_Size() int {
	return xxx_messageInfo_SyncPublicInboxMsgRsp.Size(m)
}
func (m *SyncPublicInboxMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPublicInboxMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPublicInboxMsgRsp proto.InternalMessageInfo

func (m *SyncPublicInboxMsgRsp) GetMsg() []*im.Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MsgNotify struct {
	InboxID              int64    `protobuf:"varint,1,opt,name=inboxID,proto3" json:"inboxID,omitempty"`
	Seq                  int64    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNotify) Reset()         { *m = MsgNotify{} }
func (m *MsgNotify) String() string { return proto.CompactTextString(m) }
func (*MsgNotify) ProtoMessage()    {}
func (*MsgNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d1025130c0524fd, []int{6}
}

func (m *MsgNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNotify.Unmarshal(m, b)
}
func (m *MsgNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNotify.Marshal(b, m, deterministic)
}
func (m *MsgNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNotify.Merge(m, src)
}
func (m *MsgNotify) XXX_Size() int {
	return xxx_messageInfo_MsgNotify.Size(m)
}
func (m *MsgNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNotify.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNotify proto.InternalMessageInfo

func (m *MsgNotify) GetInboxID() int64 {
	if m != nil {
		return m.InboxID
	}
	return 0
}

func (m *MsgNotify) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func init() {
	proto.RegisterType((*PullMsgReq)(nil), "mua.im.job.PullMsgReq")
	proto.RegisterType((*PullMsgRsp)(nil), "mua.im.job.PullMsgRsp")
	proto.RegisterType((*SyncPrivateInboxMsgReq)(nil), "mua.im.job.SyncPrivateInboxMsgReq")
	proto.RegisterType((*SyncPrivateInboxMsgRsp)(nil), "mua.im.job.SyncPrivateInboxMsgRsp")
	proto.RegisterType((*SyncPublicInboxMsgReq)(nil), "mua.im.job.SyncPublicInboxMsgReq")
	proto.RegisterType((*SyncPublicInboxMsgRsp)(nil), "mua.im.job.syncPublicInboxMsgRsp")
	proto.RegisterType((*MsgNotify)(nil), "mua.im.job.MsgNotify")
}

func init() { proto.RegisterFile("mua/im_job.proto", fileDescriptor_8d1025130c0524fd) }

var fileDescriptor_8d1025130c0524fd = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xa6, 0x66, 0x73, 0xfa, 0xe6, 0x61, 0xbc, 0xb9, 0x51, 0x0a, 0xc2, 0xcc, 0x69, 0x22, 0x74,
	0x30, 0xc1, 0x1f, 0x57, 0xf1, 0x32, 0x61, 0x32, 0xba, 0xdb, 0x40, 0xa4, 0x99, 0xb5, 0x64, 0x34,
	0x4b, 0xb7, 0xb4, 0xe2, 0xfc, 0xd7, 0xbd, 0x48, 0xb2, 0xea, 0xa6, 0x0d, 0x0e, 0x4f, 0x79, 0xef,
	0xcb, 0xf7, 0xf2, 0x3d, 0xbe, 0x2f, 0xd0, 0x10, 0x79, 0xd8, 0xe3, 0xe2, 0x69, 0x26, 0x99, 0x9f,
	0x2e, 0x65, 0x26, 0x11, 0x44, 0x1e, 0xfa, 0x5c, 0xf8, 0x33, 0xc9, 0xbc, 0x66, 0x71, 0x3b, 0x95,
	0x42, 0xc8, 0xf9, 0x9a, 0x40, 0xaf, 0x01, 0x46, 0x79, 0x92, 0x0c, 0x55, 0x1c, 0x44, 0x0b, 0x74,
	0xa1, 0xc6, 0xe7, 0x4c, 0xbe, 0x0d, 0xee, 0x5c, 0xa7, 0xe3, 0x74, 0x49, 0xf0, 0xd5, 0x62, 0x03,
	0x88, 0x8a, 0x16, 0xee, 0x9e, 0x41, 0x75, 0x49, 0xcf, 0x37, 0x93, 0x2a, 0xc5, 0x13, 0x20, 0x42,
	0xc5, 0x66, 0xaa, 0xde, 0xaf, 0xfb, 0x85, 0xac, 0xbe, 0xd4, 0x38, 0x4d, 0xa0, 0x3d, 0x5e, 0xcd,
	0xa7, 0xa3, 0x25, 0x7f, 0x0d, 0xb3, 0x68, 0xa0, 0x1f, 0x2d, 0x24, 0x1b, 0x40, 0x72, 0xfe, 0x5c,
	0xc8, 0xe9, 0xb2, 0x2c, 0x85, 0x08, 0x95, 0x34, 0x8c, 0x23, 0x97, 0x74, 0x9c, 0x6e, 0x35, 0x30,
	0x35, 0x7a, 0x70, 0xa0, 0xcf, 0x31, 0x7f, 0x8f, 0xdc, 0x8a, 0xc1, 0xbf, 0x7b, 0x3a, 0xb4, 0xab,
	0x6d, 0xaf, 0x49, 0x6c, 0x6b, 0xe2, 0x31, 0x54, 0x33, 0x99, 0x85, 0x89, 0x11, 0xaf, 0x06, 0xeb,
	0x86, 0x9e, 0x41, 0xcb, 0x3c, 0x97, 0xb3, 0x84, 0x4f, 0xff, 0xdc, 0x9d, 0x5e, 0x42, 0x4b, 0x95,
	0xa9, 0x3b, 0x85, 0xe9, 0x15, 0x1c, 0x0e, 0x55, 0xfc, 0x20, 0x33, 0xfe, 0xb2, 0xfa, 0x4f, 0x0a,
	0xfd, 0x0f, 0x07, 0xc8, 0xbd, 0x64, 0x78, 0x03, 0xb5, 0x22, 0x0d, 0x6c, 0xfb, 0x9b, 0xd0, 0xfd,
	0x4d, 0xb8, 0x9e, 0x15, 0x57, 0x29, 0x3e, 0x42, 0xd3, 0xe2, 0x16, 0xd2, 0x6d, 0xba, 0x3d, 0x3c,
	0x6f, 0x27, 0x47, 0xa5, 0x38, 0x01, 0x2c, 0xbb, 0x87, 0xa7, 0xa5, 0xc9, 0xdf, 0xee, 0x7a, 0x3f,
	0x28, 0x56, 0x57, 0x6f, 0x8f, 0x26, 0xb0, 0xfe, 0xd4, 0xbd, 0x99, 0x64, 0x6c, 0xdf, 0x7c, 0xe9,
	0x8b, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x56, 0x70, 0xc5, 0x07, 0x03, 0x00, 0x00,
}
